import type { ClassifiedCommit } from './types';
import { applyBump } from './semver';

const LABEL: Record<string, string> = {
  major: 'Breaking',
  minor: 'Added',
  patch: 'Fixed',
  none: 'Internal',
};

export function buildChangelog(repoFullName: string, commits: ClassifiedCommit[]): string {
  // Walk chronologically, group commits by version they shipped under.
  let version = '0.0.0';
  const groups = new Map<string, ClassifiedCommit[]>();
  for (const c of commits) {
    const next = applyBump(version, c.bump);
    const v = next === version ? version : next;
    if (!groups.has(v)) groups.set(v, []);
    groups.get(v)!.push(c);
    version = next;
  }

  const versions = [...groups.keys()].reverse();
  const out: string[] = [`# Changelog — ${repoFullName}`, '', 'Inferred semver history. Generated by VersionLens.', ''];

  for (const v of versions) {
    out.push(`## ${v}`);
    const buckets: Record<string, string[]> = { major: [], minor: [], patch: [], none: [] };
    for (const c of groups.get(v)!) {
      const first = c.message.split('\n', 1)[0];
      buckets[c.bump].push(`- ${first} (\`${c.sha.slice(0, 7)}\`)`);
    }
    for (const k of ['major', 'minor', 'patch', 'none'] as const) {
      if (buckets[k].length === 0) continue;
      out.push('', `### ${LABEL[k]}`, ...buckets[k]);
    }
    out.push('');
  }
  return out.join('\n');
}
